# This is a basic workflow to help you get started with Actions

name: MacOS Build CI

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.0
      # Runs a set of commands using the runners shell
      # Runs a set of commands using the runners shell
      - name: script run line haha
        run: |
          haxelib setup ~/haxelib
          haxelib install hxcpp > /dev/null
          haxelib install lime
          haxelib install openfl
          haxelib --never install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib install flixel-ui
          haxelib install flixel-addons
          haxelib install tjson
          haxelib install hxjsonast
          haxelib install hscript
          haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git flixel https://github.com/BushsHaxs/flixel
          haxelib install hxcpp-debug-server
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib run lime rebuild extension-webm mac
          haxelib git polymod https://github.com/ThatDisabledKid/polymod
          haxelib install newgrounds
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git linc_luajit https://github.com/ThatDisabledKid/linc_luajit
          haxelib install actuate                                                                                             
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib list
      - name: Building
        run: |
          haxelib run lime build mac
        
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
          
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: MacPort
          path: export/release/macos/bin
